sudo: false

language: python

python:
  - '3.4'
  - '3.5'
  - '3.6'

cache: pip

services:
  - docker

install:
  - docker-compose pull
  - docker-compose build
  - pip install -r requirements.txt

before_script:
  - docker-compose up -d
  - sh wait-for-url.sh http://localhost:8080/ echo "Ready!"

script:
  - behave
  - echo "Finished!"
  
after_script:
  - docker-compose down -v
