#
sudo: false

language: python

services:
  - docker

install:
  - docker-compose build

before_script:
  - docker-compose pull
  - docker-compose up -d
  - sh wait-for-url.sh http://localhost:8080/ echo "Ready!"

script:
  - docker images
  - docker ps -a

after_script:
  - docker-compose down -v
