sudo: false

# Paired with "Build pushed branches" and "Build pushed pull requests" setting
# to limit builds to pushes to master branch and PRs.
branches:
  only: 
    - master

language: python

python:
  - '3.5'
  - '3.6'

cache: pip

services:
  - docker

# Add oidc to /etc/hosts as an alias for localhost
addons:
  hosts:
    - oidc

install:
  - docker-compose -f docker-compose-test.yml pull
  - pip install -e test[dev]

before_script:
  - docker-compose -f docker-compose-test.yml up -d
  - sh test/wait-for-url.sh http://oidc:8080/ echo "oidc ready!"

script:
  - behave
  
after_script:
  - docker-compose -f docker-compose-test.yml down -v
